{% set name = "libvulkan-loader" %}
{% set version = "1.4.304.0" %}

package:
  name: {{ name }}
  version: {{ version }}

# For this repo, v**** tags exists, but apparently the stable tags (the one corresponding to versions
# that are available for download at https://vulkan.lunarg.com/sdk/home) are the vulkan-sdk-*** ones
# See https://github.com/KhronosGroup/Vulkan-Headers#version-tagging-scheme
source:
  url: https://github.com/KhronosGroup/Vulkan-Loader/archive/refs/tags/vulkan-sdk-{{ version }}.tar.gz
  sha256: 975ac2976276964d5bfd8e97b28aab85f651b225fa152ba415067f7d4443996f
  patches:
    - disable_macos_framework.patch

build:
  number: 0
  ignore_run_exports_from:
    # only the headers are used by the feedstock
    - libxcb

requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - python
    - pkg-config
  host:
    - libvulkan-headers {{ version }}
    - libxcb  # [linux]
    - xorg-libx11  # [linux]
    - xorg-libxrandr  # [linux]
  run_constrained:
    - libvulkan-headers {{ version }}

test:
  commands:
    - test -f ${PREFIX}/lib/libvulkan${SHLIB_EXT}  # [unix]
    - test ! -e ${PREFIX}/loader/vulkan.framework  # [osx]
    - if not exist %LIBRARY_LIB%\\vulkan-1.lib exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\vulkan-1.dll exit 1  # [win]

about:
  home: https://github.com/KhronosGroup/Vulkan-Loader
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Khronos official Vulkan ICD desktop loader for Windows, Linux, and MacOS.

extra:
  feedstock-name: vulkan-loader
  recipe-maintainers:
    - traversaro
